<Project>

  <!-- Paths -->
  <PropertyGroup>
    <Root>$(MSBuildThisFileDirectory)</Root>
  </PropertyGroup>

  <!-- Build Settings -->
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <!-- Product Package Versions -->
  <PropertyGroup>
    <CloudtoidFrameworkVersion>1.0.121</CloudtoidFrameworkVersion>
    <CloudtoidCodeAnalysisVersion>1.0.28</CloudtoidCodeAnalysisVersion>
    <MicrosoftExtensionsVersion>10.0.12</MicrosoftExtensionsVersion>
  </PropertyGroup>

  <!-- Test Package Versions -->
  <PropertyGroup>
    <MicrosoftDotNetTestSdk>18.10.0</MicrosoftDotNetTestSdk>
    <MSTestVersion>4.4.0</MSTestVersion>
    <NSubstituteVersion>6.2.0</NSubstituteVersion>
    <FluentAssertionsVersion>8.10.0</FluentAssertionsVersion>
    <CoverletVersion>10.0.1</CoverletVersion>
  </PropertyGroup>

  <!-- Package dependencies -->
  <ItemGroup>
    <PackageReference Include="Cloudtoid.Framework" Version="$(CloudtoidFrameworkVersion)" />
    <PackageReference Include="Cloudtoid.CodeAnalysis" Version="$(CloudtoidCodeAnalysisVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MicrosoftExtensionsVersion)" />
  </ItemGroup>

</Project>