name: publish

on:
  push:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
   
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            7.0.x

      - name: Build and Test
        run: dotnet test -c Release UrlPattern.sln

      - name: Pack
        run: dotnet pack -c Release --no-build --output . --version-suffix ${{github.run_number}} src/Cloudtoid.UrlPattern/Cloudtoid.UrlPattern.csproj 

      - name: Push
        run: dotnet nuget push Cloudtoid.UrlPattern.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nuget_org_api_key }}